name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-dev python3-pip python3-setuptools build-essential libssl-dev libffi-dev libxml2-dev libxslt1-dev zlib1g-dev
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install Cython==0.29.33 buildozer
      
      - name: Create buildozer.spec (if not exists)
        run: |
          if [ ! -f buildozer.spec ]; then
            cat > buildozer.spec << EOF
[app]
title = FoodDeliveryApp
package.name = fooddelivery
package.domain = com.fooddelivery
version = 0.1
source.dir = .
entrypoint = main.py
android.permissions = INTERNET

[buildozer]
log_level = 2
warn_on_root = 0

[app:android]
requirements = python3,kivy==2.1.0,pillow,requests
android.api = 31
android.minapi = 21
android.sdk = 31
android.ndk = 25.2.9519653
android.build_tools_version = 31.0.0
pip_index_url = https://mirrors.aliyun.com/pypi/simple/
android.accept_sdk_license = True
EOF
          fi
      
      - name: Create main.py (if not exists)
        run: |
          if [ ! -f main.py ]; then
            cat > main.py << EOF
from kivy.app import App
from kivy.uix.label import Label

class FoodDeliveryApp(App):
    def build(self):
        return Label(text='Food Delivery App')

if __name__ == '__main__':
    FoodDeliveryApp().run()
EOF
          fi
      
      - name: Build APK
        run: |
          echo 'y' | buildozer android debug
      
      - name: Find APK file
        run: |
          mkdir -p output
          find . -name "*.apk" -exec cp {} output/ \;
          ls -la output/
      
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: fooddelivery-app
          path: output/*.apk
          retention-days: 30
          
      - name: Release APK Publisher
        uses: nightcrawler-/action-release-apk@1.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}